### ISSUE TITLE
Sia Size calculation for Large Files is Incorrect

### ISSUE THREAD

**Issue by MSevey** [DaWe35/Sia-storage-pre-analyser#1]
As mentioned on the Sia Gitlab MR the calculation for the large files isn't 100% accurate. If the file is 41MB for example, Sia will upload 80MB because that extra 1MB starts a second chunk. You can probably pull the siaSize calculation out of the if else and just do the following:
```
numChunks := int(size/minFileSize) + 1
siaSize += numChunks * minFileSize
```

**Comment by DaWe35** [comment]
Thank you, I'll update

**Comment by MSevey** [comment]
sorry quick change,
should be 
```
numChunks := int(size/minFileSize)
if size % minFileSize != 0 {
  numChunks++
}
siaSize += numchunks * minFileSize
```

**Comment by MSevey** [comment]
basically anytime the file is not perfectly set to the chunk size it will round up a chunk size
